### PR TITLE
Allow to specify I18n scope leaf key for errors

### PR DESCRIPTION
**Pull request by charlie-wasp**
Addressing #15 

Not sure about method name though :)

### CODE REVIEW

**Comment by nepalez** [comment]
@charlie-wasp  Thank you!
I'm ok with the idea to fully customize the scope, but...
why don't we provide class method `scope` and drop both the `root_scope` and `scope_leaf_key`?

**Comment by nepalez** [comment]
Well, this solution wouldn't be backward-compatible, but we could just up the version and update our projects (cc @gzigzigzeo)

**Comment by charlie-wasp** [comment]
Yeah, backward compatibility is the point here. You said me to do not forget about it in the issue #15  discussion, so I didn't 😄 

Also, `root_scope` is inherited, while `scope_leaf_key` is not, which can be more flexible. If we'll provide only `scope` setter, users won't be able to set specific root scope once for all policies, instead they should set `scope` in each policy class. Don't know, how important this is

**Comment by nepalez** [comment]
Well, lets keep it, but rename to `leaf_scope` for consistency

**Comment by charlie-wasp** [comment]
Long time no see 😅 Finally I put my hands on it

**Comment by nepalez** [comment]
@charlie-wasp sorry man, but I think this PR became stale after changes made by @Envek

**Pull request closed without merging**
